### ISSUE TITLE
Add gpt-3.5-turbo New Model

### ISSUE THREAD

**Issue by revbin** [conghaonet/hao_chatgpt#1]
Hi

can you please add the new Model **gpt-3.5-turbo**.

thanks in advance

**Comment by Caqil** [comment]
+1

**Comment by conghaonet** [comment]
The model gpt-3.5-turbo is now supported.
[Releases / v1.2.0](https://github.com/conghaonet/hao_chatgpt/releases/tag/v1.2.0)
