### ISSUE TITLE
How about setting the API key on the Profile or Settings screen?

### ISSUE THREAD

**Issue by BlueBirdBack** [conghaonet/hao_chatgpt#2]
Considering that setting the API key in a .yaml file can be seen as hard-coding, what if we place it on the Profile or Settings screen instead?

**Comment by conghaonet** [comment]
You can add a new API key in the 'API keys' section of the settings menu.
![image](https://user-images.githubusercontent.com/4373795/225526691-9e22d3bf-b6c2-4696-bcba-f35c6f6dde6e.png)

**Comment by BlueBirdBack** [comment]
@conghaonet Thank you. My bad.
